test to solve errors from Netlify
ERROR Plugin load failed: hexo-renderer-marked
Error: Cannot find module '../highlight_alias.json'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)